import { SWRConfig } from "swr";
import axios from 'axios';
import Head from "next/head";
import "dotenv/config";
import Layout from "../components/layout";
import Column from "../components/column";
import { GetServerSidePropsContext } from "next";
import { IDiscussion } from "../lib/types/adapter";
import DiscussionFlow from "../components/discussionFlow";
import { unstable_serialize } from 'swr/infinite';
import Nav from "../components/nav";

const PAGE_SIZE = 1;

const fetcher = (url: string) => axios.get(url).then(res => res.data)

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/discussions?first=${PAGE_SIZE}`);
  const data = await res.json();
  const { discussionNodes, totalCount} = data || {};

  const propsData = {
    discussionNodes,
    totalCount,
  }
  console.log({
    fallback: {
      [`/api/discussions?first=${PAGE_SIZE}`]: propsData
    }
  })
  return {
    props: {
      ...propsData,
      fallback: {
        // '/api/discussions?first=1': propsData
        [unstable_serialize(()=>`/api/discussions?first=${PAGE_SIZE}`)]: [propsData]
      }
    }, // will be passed to the page component as props
  };
}

interface PropsData {
  discussions: IDiscussion[];
  totalCount: number;
}
interface IProps extends PropsData{
  fallback: {
    [key:string]: PropsData
  }
}

export default function Home(props:IProps) {
  return (
    <SWRConfig value={{ 
      fallback: props.fallback,
      fetcher
      }}>
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Column extend="lg:w-1/4 md:w-88px sm:w-88px xs:hidden shrink-0 relative">
        <div className="fixed top-0 h-screen overflow-hidden">
          <Nav />
        {/* <div className="bg-blue-400 w-10 h-10 m-4"></div>
        <nav className="mx-4">
          <div>Home</div>
          <div>Books & Magazines</div>
          <div>3d library</div>
          <Link href="/blog">Blog</Link>
        </nav> */}
          </div>
      </Column>
      <main className="flex flex-row flex-1">
      <Column extend="lg:w-2/3 md:w-2/3 sm:w-full w-full">
          <div className="flex flex-row justify-between items-center mx-4 my-2">
            <h1 className="text-3xl">The Black Box Recorder</h1>
            <div>filter</div>
          </div>
          <DiscussionFlow />
      </Column>
      <Column extend="lg:w-1/3 md:w-1/3 lg:block md:block sm:hidden xs:hidden h-full ">
        <div className="bg-green-200 sticky bottom-0 top-0">
          <aside className="m-4" >
            <h2 className="text-xl">What&#39;s trending in my life</h2>
            <div>Wabi-Sabi</div>
            <div>How to master drawing</div>
            <div>manifest</div>
          </aside>
          <aside className="m-4">
            music for today
            <div>ALINE SUPERSTAR by Beyonce</div>
          </aside>
          <footer className="mx-4">2022@tbbr.io</footer>
        </div>
      </Column>
      </main>
      <div className="bg-green-400 absolute bottom-0 hidden xs:flex flex-row w-full">
        bottom
      </div>
    </Layout>
    </SWRConfig>
  );
}
