import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/layout";
import Column from "../components/column";
import Comment from "../components/comment";

export async function getServerSideProps(context) {
  const res = await fetch(`http://localhost:3001/api/github`);
  const data = await res.json();

  // add cursor to the correct discussion
  const { discussions = {} } = data || {};
  const { nodes = [], edges = [] } = discussions || {};
  const discussionNodes = nodes.map((node, index) => {
    const { cursor } = edges[index] || {};
    node.cursor = cursor;
    return node;
  });

  return {
    props: {
      discussions: discussionNodes,
      totalCount: discussions.totalCount,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const [discussions, setDiscussions] = useState(props?.discussions ?? []);

  return (
    <Layout extend={"flex-row"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Column extend="lg:w-1/4 md:w-88px sm:w-88px xs:hidden">
        <div className="bg-blue-400 w-10 h-10 m-4"></div>
        <nav className="mx-4">
          <div>Home</div>
          <div>Explore</div>
          <Link href="/blog">Blog</Link>
        </nav>
      </Column>
      <Column extend="lg:w-1/2 md:w-2/3 sm:w-full w-full">
        <main>
          <div className="flex flex-row justify-between items-center mx-4 my-2">
            <h1 className="text-3xl">The Black Box Recorder</h1>
            <div>filter</div>
          </div>
          <div className="mx-6">
            {discussions.map((node) => {
              return (
                <div
                  key={node.id}
                  dangerouslySetInnerHTML={{ __html: node.bodyHTML }}
                />
              );
            })}
          </div>
        </main>
      </Column>
      <Column extend="lg:w-1/4 md:w-1/3 sm:w-1/3 xs:hidden">
        <div>
          <aside className="m-4">
            <h2 className="text-xl">What&#39;s trending in my life</h2>
            <div>Wabi-Sabi</div>
            <div>How to master drawing</div>
            <div>manifest</div>
          </aside>
          <aside className="m-4">
            music for today
            <div>ALINE SUPERSTAR by Beyonce</div>
          </aside>
          <footer className="mx-4">2022@tbbr.io</footer>
        </div>
      </Column>
      {/* <Comment /> */}
      <div className="bg-green-400 absolute bottom-0 hidden xs:flex flex-row w-full">
        bottom
      </div>
    </Layout>
  );
}
